spring:
  datasource:
    url: jdbc:mysql://localhost:3306/asset_track
    username: root
    password: 1Qazimodo237!

  sql:
    init:
      mode: always
      continue-on-error: false
      data-locations: classpath:schema.sql


server:
  port: 9091
  address: 0.0.0.0