spring:
  datasource:
    url: jdbc:mysql://localhost:3306/asset_track
    username: root
    password: 1Qazimodo237!
  jpa:
    open-in-view: false

  sql:
    init:
      mode: always
      continue-on-error: false
      schema-locations:
        - classpath:schema.sql
        - classpath:init.sql


server:
  port: 9091
  address: 0.0.0.0




