spring:
  datasource:
    url: jdbc:mysql://localhost:3306/asset_track
    username: root
    password: 1Qazimodo237!
  jpa:
    open-in-view: false

  sql:
    init:
      mode: always
      continue-on-error: false
      schema-locations:
        - classpath:database/schema.sql
        - classpath:database/init.sql
        - classpath:database/kst.sql
        - classpath:database/products.sql
  mail:
    host: smtp.gmail.com
    port: 587
    username: asset.track.pro@gmail.com
    password: ubum fcfe xntw xcxq
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9091
  address: 0.0.0.0



springdoc:
  override-with-generic-response: false
