spring:
  datasource:
    url: jdbc:mysql://localhost:3306/csmm
    username: root
    password: 1Qazimodo237!

  sql:
    init:
      mode: always
      continue-on-error: false
      data-locations: classpath:init_auth.sql
