DROP TABLE IF EXISTS event_products;
DROP TABLE IF EXISTS unknown_products;


DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS invents;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS subtypes;
DROP TABLE IF EXISTS types;
DROP TABLE IF EXISTS units;
DROP TABLE IF EXISTS asset_statuses;
DROP TABLE IF EXISTS ksts;
DROP TABLE IF EXISTS mpks;
DROP TABLE IF EXISTS branches;
DROP TABLE IF EXISTS token;
DROP TABLE IF EXISTS company;
DROP TABLE IF EXISTS logs;
DROP TABLE IF EXISTS notifications;


DROP TABLE IF EXISTS token;
DROP TABLE IF EXISTS users;
