INSERT IGNORE INTO ksts (is_active, num, kst) VALUES
(false, '0', 'GRUNTY'),
(false, '01', 'UŻYTKI ROLNE'),
(false, '010', 'Grunty orne'),
(false, '011', 'Sady'),
(false, '012', 'Łąki trwałe'),
(false, '013', 'Pastwiska trwałe'),
(false, '014', 'Grunty rolne zabudowane'),
(false, '015', 'Grunty pod stawami'),
(false, '016', 'Grunty pod rowami'),
(false, '02', 'GRUNTY LEŚNE'),
(false, '020', 'Lasy'),
(false, '021', 'Grunty zadrzewione i zakrzewione'),
(false, '03', 'GRUNTY ZABUDOWANE I ZURBANIZOWANE'),
(false, '030', 'Tereny mieszkaniowe'),
(false, '031', 'Tereny przemysłowe'),
(false, '032', 'Inne tereny zabudowane'),
(false, '033', 'Zurbanizowane tereny niezabudowane'),
(false, '034', 'Tereny rekreacyjno-wypoczynkowe'),
(false, '035', 'Użytki kopalne'),
(false, '036', 'Tereny komunikacyjne'),
(false, '04', 'Użytki ekologiczne'),
(false, '040', 'Użytki ekologiczne'),
(false, '05', 'Tereny różne'),
(false, '050', 'Tereny różne'),
(false, '06', 'Nieużytki'),
(false, '060', 'Nieużytki'),
(false, '07', 'GRUNTY POD WODAMI'),
(false, '070', 'Grunty pod wodami, z wyłączeniem gruntów pod wodami powstałych w wyniku użytkowania urządzeń melioracji wodnych'),
(false, '071', 'Grunty pod wodami powstałe w wyniku użytkowania urządzeń melioracji wodnych'),
(false, '11', 'BUDYNKI MIESZKALNE'),
(false, '10', 'BUDYNKI NIEMIESZKALNE'),
(false, '101', 'Budynki przemysłowe'),
(false, '102', 'Budynki transportu i łączności'),
(false, '103', 'Budynki handlowo-usługowe'),
(false, '104', 'Zbiorniki, silosy i budynki magazynowe'),
(false, '105', 'Budynki biurowe'),
(false, '106', 'Budynki szpitali i inne budynki opieki zdrowotnej'),
(false, '107', 'Budynki oświaty, nauki i kultury oraz budynki sportowe'),
(false, '108', 'Budynki produkcyjne, usługowe i gospodarcze dla rolnictwa'),
(false, '109', 'Pozostałe budynki niemieszkalne'),
(false, '1', 'BUDYNKI I LOKALE ORAZ SPÓŁDZIELCZE PRAWO DO LOKALU UŻYTKOWEGO I SPÓŁDZIELCZE WŁASNOŚCIOWE PRAWO DO LOKALU MIESZKALNEGO'),
(false, '110', 'BUDYNKI MIESZKALNE'),
(false, '12', 'LOKALE, SPÓŁDZIELCZE PRAWO DO LOKALU UŻYTKOWEGO ORAZ SPÓŁDZIELCZE WŁASNOŚCIOWE PRAWO DO LOKALU MIESZKALNEGO'),
(false, '121', 'Lokale niemieszkalne, spółdzielcze prawo do lokalu użytkowego'),
(false, '122', 'Lokale mieszkalne, spółdzielcze własnościowe prawo do lokalu mieszkalnego'),
(false, '2', 'OBIEKTY INŻYNIERII LĄDOWEJ I WODNEJ'),
(false, '20', 'KOMPLEKSOWE BUDOWLE NA TERENACH PRZEMYSŁOWYCH'),
(false, '200', 'Budowle dla górnictwa i kopalnictwa'),
(false, '201', 'Budowle na terenach elektrowni'),
(false, '202', 'Budowle na terenach zakładów chemicznych'),
(false, '203', 'Budowle na terenach zakładów przemysłu metalowego'),
(false, '204', 'Budowle na terenach zakładów przemysłu ceramicznego i wydobywczego'),
(false, '205', 'Budowle na terenach przemysłu elektromaszynowego'),
(false, '206', 'Budowle na terenach przemysłu spożywczego'),
(false, '207', 'Budowle na terenach przemysłu skórzanego i włókienniczego'),
(false, '208', 'Budowle na terenach przemysłu lekkiego'),
(false, '209', 'Budowle na terenach przemysłu drzewnego i papierniczego'),
(false, '210', 'Budowle na terenach przemysłu materiałów budowlanych i szklarskiego'),
(false, '211', 'Budowle na terenach zakładów przemysłu maszynowego i urządzeń'),
(false, '212', 'Budowle na terenach zakładów przemysłu gumowego i tworzyw sztucznych'),
(false, '213', 'Budowle na terenach zakładów przemysłu poligraficznego'),
(false, '214', 'Budowle na terenach zakładów przemysłu metalowego'),
(false, '215', 'Budowle na terenach przemysłu chemicznego'),
(false, '216', 'Budowle na terenach zakładów przemysłu materiałów wybuchowych'),
(false, '217', 'Budowle na terenach zakładów przemysłu farmaceutycznego'),
(false, '218', 'Budowle na terenach zakładów przemysłu maszynowego'),
(false, '219', 'Budowle na terenach zakładów przemysłu elektronicznego'),
(false, '22', 'DROGI'),
(false, '220', 'Autostrady i drogi ekspresowe'),
(false, '221', 'Drogi krajowe'),
(false, '222', 'Drogi wojewódzkie'),
(false, '223', 'Drogi powiatowe'),
(false, '224', 'Drogi gminne'),
(false, '225', 'Drogi dojazdowe'),
(false, '226', 'Drogi wewnętrzne i dojazdowe zakładów przemysłowych'),
(false, '227', 'Inne drogi publiczne'),
(false, '228', 'Drogi eksploatacyjne i robotnicze w lasach'),
(false, '23', 'KOLEJE'),
(false, '230', 'Koleje z wyłączeniem torowisk kolejowych'),
(false, '231', 'Torowiska kolejowe'),
(false, '24', 'TERENY LOTNISKOWE'),
(false, '240', 'Tereny lotniskowe'),
(false, '25', 'URZĄDZENIA SPORTOWO-REKREACYJNE'),
(false, '250', 'Obiekty sportowe'),
(false, '251', 'Obiekty rekreacyjno-wypoczynkowe'),
(false, '26', 'URZĄDZENIA HYDROTECHNICZNE'),
(false, '260', 'Stacje pomp i przepompownie wód'),
(false, '261', 'Jazy, śluzy i zapory'),
(false, '262', 'Węzły regulacji wód i urządzenia melioracji wodnych'),
(false, '263', 'Zbiorniki retencyjne i przeciwpowodziowe'),
(false, '264', 'Tamy i wały przeciwpowodziowe'),
(false, '265', 'Urządzenia i budowle do gospodarki wodno-ściekowej'),
(false, '266', 'Kanały i rowy melioracyjne'),
(false, '267', 'Oczyszczalnie ścieków'),
(false, '27', 'URZĄDZENIA INŻYNIERII WODNEJ I PRZYBRZEŻNEJ'),
(false, '270', 'Urządzenia do zaopatrzenia w wodę'),
(false, '271', 'Urządzenia do usuwania ścieków i oczyszczalnie ścieków'),
(false, '272', 'Urządzenia do regulacji poziomu wody i hydroenergetyczne'),
(false, '273', 'Urządzenia do ochrony brzegów i dno rzeki'),
(false, '274', 'Urządzenia do zabezpieczania brzegów i dno rzeki'),
(false, '275', 'Urządzenia do ochrony przed powodzią'),
(false, '276', 'Urządzenia do uzdatniania brzegów'),
(false, '277', 'Urządzenia do gospodarowania odpadami i ochrony środowiska'),
(false, '278', 'Urządzenia do gospodarowania i ochrony przed hałasem'),
(false, '279', 'Urządzenia do gospodarowania wodą i środowiskiem'),
(false, '28', 'URZĄDZENIA INŻYNIERII LĄDOWEJ'),
(false, '280', 'Urządzenia drogowe i kolejowe'),
(false, '281', 'Urządzenia drogowe'),
(false, '282', 'Urządzenia kolejowe'),
(false, '283', 'Urządzenia do melioracji gruntów'),
(false, '284', 'Urządzenia do ochrony gruntów'),
(false, '285', 'Urządzenia do gospodarowania gruntem'),
(false, '286', 'Urządzenia do zabezpieczania gruntu'),
(false, '29', 'URZĄDZENIA INŻYNIERII LĄDOWEJ I WODNEJ NIEKLASYFIKOWANE INDEKSAMI 28 I 27'),
(false, '290', 'Urządzenia inżynierii lądowej i wodnej nieklasyfikowane indeksami 28 i 27'),
(false, '3', 'URZĄDZENIA TECHNICZNE'),
(false, '30', 'URZĄDZENIA TECHNICZNE'),
(false, '300', 'Maszyny i urządzenia techniczne'),
(false, '301', 'Maszyny budowlane'),
(false, '302', 'Maszyny rolnicze'),
(false, '303', 'Maszyny do robót ziemnych'),
(false, '304', 'Maszyny do prac ziemnych i betonowych'),
(false, '305', 'Maszyny i urządzenia do robót ziemnych i drogowych'),
(false, '306', 'Maszyny i urządzenia do robót leśnych i pielęgnacji terenów zielonych'),
(false, '307', 'Maszyny i urządzenia do robót kamieniarskich'),
(false, '308', 'Maszyny i urządzenia do prac brukarskich'),
(false, '309', 'Maszyny i urządzenia do prac mostowych'),
(false, '31', 'URZĄDZENIA TECHNICZNE I TECHNOLOGICZNE'),
(false, '310', 'Maszyny i urządzenia technologiczne'),
(false, '311', 'Maszyny i urządzenia technologiczne dla budownictwa'),
(false, '312', 'Maszyny i urządzenia technologiczne dla przemysłu metalowego'),
(false, '313', 'Maszyny i urządzenia technologiczne dla przemysłu ceramicznego i wydobywczego'),
(false, '314', 'Maszyny i urządzenia technologiczne dla przemysłu elektromaszynowego'),
(false, '315', 'Maszyny i urządzenia technologiczne dla przemysłu spożywczego'),
(false, '316', 'Maszyny i urządzenia technologiczne dla przemysłu skórzanego i włókienniczego'),
(false, '317', 'Maszyny i urządzenia technologiczne dla przemysłu lekkiego'),
(false, '318', 'Maszyny i urządzenia technologiczne dla przemysłu drzewnego i papierniczego'),
(false, '319', 'Maszyny i urządzenia technologiczne dla przemysłu materiałów budowlanych i szklarskiego'),
(false, '32', 'URZĄDZENIA TECHNICZNE DLA PRZEMYSŁU I ROLNICTWA'),
(false, '320', 'Urządzenia techniczne dla przemysłu i rolnictwa'),
(false, '321', 'Urządzenia techniczne dla przemysłu'),
(false, '322', 'Urządzenia techniczne dla rolnictwa'),
(false, '33', 'URZĄDZENIA TECHNICZNE I TECHNOLOGICZNE NIEKLASYFIKOWANE INDEKSAMI 30 I 31'),
(false, '330', 'Urządzenia techniczne i technologiczne nieklasyfikowane indeksami 30 i 31'),
(false, '34', 'MASZYNY'),
(false, '35', 'MASZYNY I URZĄDZENIA DO PRODUKCJI'),
(false, '36', 'MASZYNY I URZĄDZENIA DO OBRÓBKI'),
(false, '37', 'MASZYNY I URZĄDZENIA DO SPALANIA I REKUPERACJI'),
(false, '38', 'MASZYNY I URZĄDZENIA DO TRANSPORTU I ZAŁADUNKU'),
(false, '39', 'MASZYNY I URZĄDZENIA DO WYWOZU I ROZŁADUNKU'),
(false, '4', 'URZĄDZENIA OCHRONY ŚRODOWISKA I ENERGETYKI'),
(false, '40', 'URZĄDZENIA OCHRONY ŚRODOWISKA I ENERGETYKI'),
(false, '400', 'Środki ochrony powietrza'),
(false, '401', 'Urządzenia przeciwdymne'),
(false, '402', 'Urządzenia ochrony przed promieniowaniem elektromagnetycznym'),
(false, '403', 'Urządzenia ochrony przed promieniowaniem radioaktywnym'),
(false, '404', 'Urządzenia ochrony przed hałasem'),
(false, '405', 'Urządzenia ochrony przed drganiami'),
(false, '406', 'Urządzenia ochrony przed zanieczyszczeniem atmosfery'),
(false, '407', 'Urządzenia ochrony przed emisją hałasu'),
(false, '408', 'Urządzenia ochrony przed emisją wibracji'),
(false, '409', 'Urządzenia ochrony przed zanieczyszczeniem wód i gleb'),
(false, '41', 'URZĄDZENIA OCHRONY ŚRODOWISKA'),
(false, '410', 'Urządzenia ochrony powietrza'),
(false, '411', 'Urządzenia ochrony wód i gleb'),
(false, '412', 'Urządzenia ochrony środowiska'),
(false, '413', 'Urządzenia ochrony przyrody'),
(false, '414', 'Urządzenia ochrony zasobów naturalnych'),
(false, '415', 'Urządzenia ochrony flory i fauny'),
(false, '416', 'Urządzenia ochrony zasobów wodnych'),
(false, '417', 'Urządzenia ochrony zasobów energetycznych'),
(false, '418', 'Urządzenia ochrony klimatu'),
(false, '419', 'Urządzenia ochrony zasobów naturalnych przed skutkami działalności człowieka'),
(false, '42', 'URZĄDZENIA ENERGETYKI'),
(false, '420', 'Urządzenia energetyki'),
(false, '421', 'Urządzenia do wytwarzania energii elektrycznej'),
(false, '422', 'Urządzenia do wytwarzania energii cieplnej'),
(false, '423', 'Urządzenia do przetwarzania energii'),
(false, '424', 'Urządzenia do transportu energii'),
(false, '425', 'Urządzenia do magazynowania energii'),
(false, '426', 'Urządzenia do przesyłu energii'),
(false, '427', 'Urządzenia do przetwarzania paliw'),
(false, '428', 'Urządzenia do magazynowania paliw'),
(false, '429', 'Urządzenia do transportu paliw'),
(false, '43', 'URZĄDZENIA ENERGETYKI I OCHRONY ŚRODOWISKA'),
(false, '430', 'Urządzenia energetyki i ochrony środowiska'),
(false, '431', 'Urządzenia do produkcji i dystrybucji energii elektrycznej'),
(false, '432', 'Urządzenia i aparaty do pasteryzacji'),
(false, '433', 'Maszyny i urządzenia do dozowania i napełniania butelek, słoi, puszek, tub itp.'),
(false, '434', 'Maszyny i urządzenia do zamykania, korkowania, etykietowania itp.'),
(false, '435', 'Maszyny i urządzenia do pakowania w kartony i torby oraz maszyny wytwarzające opakowania'),
(false, '436', 'Urządzenia do mycia i czyszczenia opakowań'),
(false, '437', 'Pozostałe maszyny, urządzenia i aparaty ogólnego zastosowania w przemyśle rolnym i spożywczym'),
(false, '44', 'MASZYNY I URZĄDZENIA DO PRZETŁACZANIA I SPRĘŻANIA CIECZY  I GAZÓW'),
(false, '440', 'Pompy nurnikowe i tłokowe'),
(false, '441', 'Pompy wirowe'),
(false, '442', 'Pompy rotacyjne'),
(false, '443', 'Pompy zębate'),
(false, '444', 'Sprężarki'),
(false, '445', 'Dmuchawy i ssawy'),
(false, '446', 'Wentylatory'),
(false, '449', 'Pozostałe maszyny i urządzenia do przetłaczania i sprężania cieczy i gazów'),
(false, '45', 'PIECE PRZEMYSŁOWE'),
(false, '450', 'Piece do przerobu surowców'),
(false, '451', 'Piece do przetwarzania paliw'),
(false, '452', 'Piece grzewcze'),
(false, '453', 'Piece topielne'),
(false, '454', 'Piece do wypalania'),
(false, '455', 'Konwertory i mieszalniki stalownicze'),
(false, '456', 'Piece indukcyjne zasilane prądem wysokiej częstotliwości do obróbki termicznej'),
(false, '46', 'URZĄDZENIA DO WYMIANY CIEPŁA'),
(false, '460', 'Wymienniki przeponowe dwupłaszczowe'),
(false, '461', 'Wymienniki przeponowe płaszczowo-rurkowe'),
(false, '462', 'Wymienniki przeponowe komorowo-grzejnikowe'),
(false, '463', 'Wymienniki przeponowe płaszczowo-wężownicowe'),
(false, '464', 'Wymienniki przeponowe dwupłaszczowo-wężownicowe'),
(false, '465', 'Wymienniki przeponowe rurowe'),
(false, '466', 'Wymienniki przeponowe kanałowe'),
(false, '469', 'Pozostałe urządzenia do wymiany ciepła'),
(false, '47', 'MASZYNY, URZĄDZENIA I APARATY DO PROCESÓW MATERIAŁOWYCH'),
(false, '470', 'Mieszalniki cieczy bezciśnieniowe z urządzeniami mieszającymi lub przesuwającymi'),
(false, '471', 'Mieszalniki cieczy na ciśnienie do 16 atm. z mechanizmami mieszającymi'),
(false, '472', 'Mieszalniki cieczy na ciśnienie powyżej 16 atm.  z mechanizmami i urządzeniami mieszającymi'),
(false, '473', 'Skrubery'),
(false, '474', 'Kolumny'),
(false, '475', 'Aparaty bębnowe'),
(false, '476', 'Aparaty walcowe skrobakowe'),
(false, '477', 'Suszarki komorowe'),
(false, '479', 'Pozostałe maszyny, urządzenia i aparaty do procesów materiałowych'),
(false, '48', 'POZOSTAŁE MASZYNY, URZĄDZENIA I APARATY OGÓLNEGO ZASTOSOWANIA'),
(false, '480', 'Elektrolizery'),
(false, '481', 'Aparaty i urządzenia do powierzchniowej obróbki metali sposobem chemicznym i elektrogalwanicznym'),
(false, '482', 'Aparaty i urządzenia do powierzchniowej obróbki metali sposobem cieplnym'),
(false, '483', 'Urządzenia do elektroerozyjnej obróbki metali'),
(false, '484', 'Maszyny i aparaty do spawania, zgrzewania, natryskiwania oraz maszyny i aparaty do cięcia przy pomocy gazu'),
(false, '485', 'Urządzenia i aparaty chłodnicze nieprzenośne'),
(false, '486', 'Urządzenia i aparaty chłodnicze przenośne'),
(false, '49', 'POZOSTAŁE MASZYNY, URZĄDZENIA I APARATY SPECJALIZOWANE  I SPECJALNE, OGÓLNEGO ZASTOSOWANIA'),
(false, '490', 'Maszyny i urządzenia do przygotowania maszynowych nośników danych oraz maszyny analityczne'),
(false, '491', 'Zespoły komputerowe'),
(false, '492', 'Samodzielne urządzenia do automatycznej regulacji  i sterowania procesami'),
(false, '493', 'Roboty'),
(false, '5', 'MASZYNY, URZĄDZENIA I APARATY SPECJALISTYCZNE'),
(false, '50', 'MASZYNY, URZĄDZENIA I APARATY DLA PRZEMYSŁU CHEMICZNEGO'),
(false, '500', 'Maszyny, urządzenia i aparaty dla przemysłu azotowego i syntezy chemicznej'),
(false, '501', 'Maszyny, urządzenia i aparaty dla przemysłu farmaceutycznego i przemysłów pokrewnych'),
(false, '502', 'Maszyny, urządzenia i aparaty dla przemysłu włókien sztucznych'),
(false, '503', 'Maszyny, urządzenia i aparaty dla przemysłu tworzyw sztucznych'),
(false, '504', 'Maszyny, urządzenia i aparaty dla przemysłu gumowego'),
(false, '505', 'Maszyny, urządzenia i aparaty dla przemysłu nieorganicznego, siarkowego i nawozów fosforowych'),
(false, '506', 'Maszyny, urządzenia i aparaty dla przemysłu gazów technicznych'),
(false, '507', 'Maszyny, urządzenia i aparaty dla przemysłu rafineryjnego'),
(false, '51', 'MASZYNY, URZĄDZENIA I APARATY WIERTNICZE, GÓRNICZE, GAZOWNICZE, ODLEWNICZE, TORFIARSKIE ORAZ GEODEZYJNE I KARTOGRAFICZNE'),
(false, '510', 'Maszyny i urządzenia wiertnicze'),
(false, '511', 'Maszyny górnicze'),
(false, '512', 'Maszyny i urządzenia do eksploatacji otworów wiertniczych'),
(false, '513', 'Maszyny i urządzenia do przeróbki mechanicznej rud i węgla'),
(false, '514', 'Maszyny i urządzenia hutnicze'),
(false, '515', 'Maszyny i urządzenia koksownicze i gazownicze'),
(false, '516', 'Maszyny i urządzenia odlewnicze'),
(false, '517', 'Maszyny i urządzenia torfiarskie'),
(false, '518', 'Aparaty i urządzenia do pomiarów i zabiegów geofizycznych, geodezyjnych, fotogrametrycznych, kartograficznych itp.'),
(false, '52', 'MASZYNY DLA PRZEMYSŁU SUROWCÓW MINERALNYCH'),
(false, '520', 'Maszyny i urządzenia dla przemysłu kamieniarskiego'),
(false, '521', 'Maszyny i urządzenia dla przemysłu mineralnego'),
(false, '522', 'Maszyny i urządzenia dla przemysłu wapienniczego i gipsowego'),
(false, '523', 'Maszyny i urządzenia dla przemysłu cementowego'),
(false, '524', 'Maszyny, urządzenia i aparaty dla przemysłu izolacyjnego i korkowego'),
(false, '525', 'Maszyny i urządzenia do produkcji ceramiki budowlanej materiałów ognioodpornych i silikatowych'),
(false, '526', 'Maszyny dla przemysłu ceramiki szlachetnej i technicznej'),
(false, '527', 'Maszyny i urządzenia do produkcji szkła i wyrobów ze szkła'),
(false, '528', 'Maszyny i urządzenia dla przemysłu materiałów ściernych'),
(false, '529', 'Maszyny, urządzenia i agregaty do produkcji innych materiałów budowlanych'),
(false, '53', 'MASZYNY DO PRODUKCJI WYROBÓW Z METALI I TWORZYW SZTUCZNYCH'),
(false, '531', 'Maszyny specjalne do produkcji wyrobów drobnej galanterii metalowej'),
(false, '532', 'Maszyny do produkcji wyrobów metalowych'),
(false, '533', 'Maszyny i urządzenia do produkcji kabli i przedmiotów elektrycznych'),
(false, '534', 'Maszyny i urządzenia do produkcji akumulatorów i baterii'),
(false, '535', 'Maszyny i urządzenia do produkcji żarówek i lamp elektronowych'),
(false, '536', 'Maszyny i aparaty do produkcji taśmy filmowej i magnetycznej, błon, płyt i papierów fotograficznych'),
(false, '537', 'Maszyny i aparaty do produkcji filmów i kopii filmowych oraz do realizacji filmów'),
(false, '538', 'Maszyny do nawijania cewek oraz izolacji silników, transformatorów i kondensatorów'),
(false, '54', 'MASZYNY, URZĄDZENIA I APARATY DO OBRÓBKI I PRZEROBU DREWNA, PRODUKCJI WYROBÓW Z DREWNA ORAZ MASZYNY, URZĄDZENIA I APARATY DLA PRZEMYSŁU PAPIERNICZEGO I POLIGRAFICZNEGO'),
(false, '540', 'Maszyny, urządzenia i aparaty do ścinki drzew oraz obróbki drewna'),
(false, '541', 'Maszyny, urządzenia i aparaty do wyrobu oklein, płyt stolarskich i sklejek'),
(false, '542', 'Maszyny, urządzenia i aparaty do wyrobu płyt pilśniowych i płyt wiórowych'),
(false, '543', 'Maszyny, urządzenia i aparaty do wyrobu zapałek'),
(false, '544', 'Maszyny, urządzenia i aparaty do wyrobu beczek, skrzyń i różnych wyrobów z drewna'),
(false, '545', 'Maszyny, urządzenia i aparaty do wyrobu celulozy'),
(false, '546', 'Maszyny i urządzenia do wyrobu papieru i tektury'),
(false, '547', 'Maszyny, urządzenia i aparaty do wyrobów papierniczych i tekturowych'),
(false, '548', 'Maszyny, urządzenia i aparaty poligraficzne'),
(false, '549', 'Maszyny i urządzenia do produkcji wyrobów z drewna lub materiałów zastępczych w połączeniu z innymi materiałami'),
(false, '55', 'MASZYNY I URZĄDZENIA DO PRODUKCJI WYROBÓW WŁÓKIENNICZYCH I ODZIEŻOWYCH ORAZ DO OBRÓBKI SKÓRY I PRODUKCJI WYROBÓW Z NIEJ'),
(false, '550', 'Maszyny do wstępnej obróbki włókien łykowych'),
(false, '551', 'Maszyny przędzalnicze'),
(false, '552', 'Maszyny do produkcji nici, sznurków i lin'),
(false, '553', 'Maszyny tkackie'),
(false, '554', 'Maszyny dziewiarskie i pończosznicze'),
(false, '555', 'Maszyny wykończalnicze i farbiarskie'),
(false, '556', 'Maszyny do produkcji filcu i artykułów z filcu'),
(false, '557', 'Maszyny szwalnicze, odzieżowe i do wyrobu guzików'),
(false, '558', 'Maszyny do produkcji skóry i wyrobów ze skóry'),
(false, '559', 'Pozostałe maszyny i urządzenia dla przemysłów włókienniczego, odzieżowego i skórzanego'),
(false, '56', 'MASZYNY, URZĄDZENIA I APARATY DLA PRZEMYSŁU ROLNEGO'),
(false, '560', 'Maszyny, urządzenia i aparaty dla przemysłu cukrowniczego'),
(false, '561', 'Maszyny, urządzenia i aparaty dla przemysłu piwowarskiego i do produkcji napoi'),
(false, '562', 'Maszyny, urządzenia i aparaty do produkcji drożdży'),
(false, '563', 'Maszyny, urządzenia i aparaty do produkcji wyrobów spirytusowych'),
(false, '564', 'Maszyny, urządzenia i aparaty do produkcji octu'),
(false, '565', 'Maszyny, urządzenia i aparaty dla przemysłu ziemniaczanego'),
(false, '566', 'Maszyny, urządzenia i aparaty dla przemysłu owocowo-warzywnego'),
(false, '567', 'Maszyny, urządzenia i aparaty dla przemysłu młynarskiego'),
(false, '568', 'Maszyny, urządzenia i aparaty dla przemysłu piekarniczego'),
(false, '57', 'MASZYNY, URZĄDZENIA I APARATY DLA PRZEMYSŁU SPOŻYWCZEGO'),
(false, '570', 'Maszyny, urządzenia i aparaty dla przemysłu cukierniczego'),
(false, '571', 'Maszyny, urządzenia i aparaty dla przemysłu koncentratów spożywczych'),
(false, '572', 'Maszyny, urządzenia i aparaty dla przemysłów tytoniowego i zielarskiego'),
(false, '573', 'Maszyny, urządzenia i aparaty dla przemysłu mięsnego'),
(false, '574', 'Maszyny, urządzenia i aparaty dla przemysłu rybnego'),
(false, '575', 'Maszyny, urządzenia i aparaty dla przemysłu tłuszczowego'),
(false, '576', 'Maszyny, urządzenia i aparaty dla przemysłu mleczarskiego'),
(false, '577', 'Maszyny, urządzenia i aparaty dla przemysłu jajczarsko-drobiarskiego'),
(false, '578', 'Maszyny, urządzenia i aparaty dla przemysłu gastronomicznego'),
(false, '579', 'Pozostałe maszyny, urządzenia i aparaty dla przemysłu spożywczego'),
(false, '58', 'MASZYNY DO ROBÓT ZIEMNYCH, BUDOWLANYCH I DROGOWYCH'),
(false, '580', 'Maszyny do robót ziemnych i fundamentowych'),
(false, '581', 'Maszyny do robót budowlanych'),
(false, '582', 'Maszyny do robót drogowych'),
(false, '583', 'Koparki i zwałowarki używane w kopalnictwie odkrywkowym'),
(false, '584', 'Maszyny do robót torowych kolejowych'),
(false, '59', 'MASZYNY, URZĄDZENIA I NARZĘDZIA ROLNICZE I GOSPODARKI LEŚNEJ'),
(false, '590', 'Maszyny i narzędzia uprawowe'),
(false, '591', 'Maszyny i urządzenia do siewu, sadzenia, nawożenia i deszczowania'),
(false, '592', 'Maszyny i narzędzia pielęgnacyjne'),
(false, '593', 'Maszyny i urządzenia do ochrony roślin'),
(false, '594', 'Maszyny i urządzenia do zbioru ziemiopłodów'),
(false, '595', 'Maszyny i urządzenia omłotowe, suszarnie i urządzenia pomocnicze'),
(false, '596', 'Maszyny i urządzenia do czyszczenia, sortowania i zaprawiania ziemiopłodów'),
(false, '597', 'Maszyny i urządzenia do przetwórstwa paszowego'),
(false, '598', 'Maszyny oraz urządzenia do chowu i hodowli zwierząt'),
(false, '599', 'Pozostałe maszyny, urządzenia i narzędzia rolnicze i dla gospodarki leśnej'),
(false, '6', 'URZĄDZENIA TECHNICZNE'),
(false, '60', 'ZBIORNIKI NAZIEMNE'),
(false, '600', 'Zbiorniki naziemne ceglane'),
(false, '601', 'Zbiorniki naziemne betonowe'),
(false, '602', 'Zbiorniki naziemne drewniane'),
(false, '603', 'Zbiorniki naziemne z tworzyw naturalnych i sztucznych'),
(false, '604', 'Zbiorniki naziemne stalowe'),
(false, '605', 'Zbiorniki naziemne z metali nieżelaznych'),
(false, '61', 'URZĄDZENIA I APARATURA ENERGII ELEKTRYCZNEJ'),
(false, '610', 'Urządzenia rozdzielcze prądu zmiennego'),
(false, '611', 'Urządzenia nastawcze prądu zmiennego i stałego'),
(false, '612', 'Aparatura prądu zmiennego'),
(false, '613', 'Stacje transformatorowe stałe i mobilne'),
(false, '614', 'Urządzenia i aparatura rozdzielcza prądu stałego'),
(false, '615', 'Aparatura prądu stałego'),
(false, '62', 'URZĄDZENIA DLA RADIOFONII I TELEWIZJI, URZĄDZENIA DLA TELEFONII I TELEGRAFII'),
(false, '620', 'Urządzenia nadawcze dla radiofonii i telewizji'),
(false, '621', 'Urządzenia odbiorcze dla radiofonii i telewizji'),
(false, '622', 'Urządzenia elektroakustyczne i elektrowizyjne'),
(false, '623', 'Urządzenia teletransmisji przewodowej'),
(false, '624', 'Urządzenia alarmowe i sygnalizacyjne'),
(false, '626', 'Urządzenia dla telefonii'),
(false, '627', 'Urządzenia dla telegrafii'),
(false, '629', 'Pozostałe urządzenia tele- i radiotechniczne'),
(false, '63', 'URZĄDZENIE ELEKTROENERGETYCZNE PRZETWÓRCZE I ZASILAJĄCE'),
(false, '630', 'Transformatory'),
(false, '631', 'Zespoły prostownikowe'),
(false, '632', 'Kondensatory statyczne'),
(false, '633', 'Baterie stacjonarnych akumulatorów elektrycznych'),
(false, '634', 'Baterie akumulatorów elektrycznych zasadowych'),
(false, '64', 'DŹWIGI I PRZENOŚNIKI'),
(false, '640', 'Dźwigi osobowe i towarowe'),
(false, '641', 'Dźwigniki, wciągarki i wciągniki przejezdne i nieprzejezdne, kołowroty, wyciągniki itp.'),
(false, '642', 'Żurawie (dźwigi przeładunkowe)'),
(false, '643', 'Przenośniki ogólnego zastosowania'),
(false, '644', 'Przenośniki kopalniane'),
(false, '645', 'Przenośniki powietrzne i wodne'),
(false, '646', 'Suwnice i wsadzarki'),
(false, '647', 'Przesuwnice, obrotnice i wywrotnice'),
(false, '648', 'Tory, towarowe kolejki linowe i dźwignice linowe'),
(false, '65', 'URZĄDZENIA PRZEMYSŁOWE'),
(false, '650', 'Przekładnie'),
(false, '652', 'Urządzenia wentylacyjne'),
(false, '653', 'Urządzenia klimatyzacyjne'),
(false, '654', 'Urządzenia do oczyszczania wody'),
(false, '655', 'Urządzenia do oczyszczania gazów'),
(false, '656', 'Urządzenia do odpopielania i odżużlania'),
(false, '657', 'Akumulatory hydrauliczne'),
(false, '658', 'Urządzenia do oczyszczania ścieków'),
(false, '659', 'Pozostałe urządzenia przemysłowe, gdzie indziej niesklasyfikowane'),
(false, '66', 'URZĄDZENIA NIEPRZEMYSŁOWE'),
(false, '660', 'Wagi pojazdowe, wagonowe i inne wbudowane'),
(false, '661', 'Urządzenia pralni i farbiarni'),
(false, '662', 'Urządzenia i aparaty projekcyjne'),
(false, '663', 'Urządzenia przeciwpożarowe'),
(false, '664', 'Urządzenia i aparatura do przeprowadzania badań technicznych'),
(false, '668', 'Urządzenia techniczne teatralne'),
(false, '669', 'Pozostałe urządzenia nieprzemysłowe'),
(false, '68', 'POZOSTAŁE URZĄDZENIA TECHNICZNE'),
(false, '681', 'Kontenery'),
(false, '682', 'Nadwozia wymienne'),
(false, '7', 'ŚRODKI TRANSPORTU'),
(false, '70', 'Tabor kolejowy naziemny'),
(false, '700', 'Tabor kolejowy naziemny'),
(false, '71', 'Tabor kolejowy podziemny'),
(false, '710', 'Tabor kolejowy podziemny'),
(false, '72', 'Tabor tramwajowy'),
(false, '720', 'Tabor tramwajowy'),
(false, '73', 'Pozostały tabor szynowy naziemny'),
(false, '730', 'Pozostały tabor szynowy naziemny'),
(false, '74', 'POJAZDY MECHANICZNE'),
(false, '740', 'Motocykle, przyczepy i wózki motocyklowe'),
(false, '741', 'Samochody osobowe'),
(false, '742', 'Samochody ciężarowe'),
(false, '743', 'Samochody specjalne'),
(false, '744', 'Pojazdy samochodowe przeznaczone konstrukcyjnie do przewozu dziewięciu lub więcej osób, włączając kierowcę'),
(false, '745', 'Trolejbusy i samochody o napędzie elektrycznym'),
(false, '746', 'Ciągniki'),
(false, '747', 'Naczepy'),
(false, '748', 'Przyczepy'),
(false, '75', 'Tabor konny'),
(false, '750', 'Tabor konny'),
(false, '76', 'POZOSTAŁY TABOR BEZSZYNOWY'),
(false, '760', 'Wózki jezdniowe z pomostem stałym o napędzie elektrycznym (akumulatorowe)'),
(false, '761', 'Wózki jezdniowe podnośnikowe z nisko podnoszoną platformą o napędzie elektrycznym  (akumulatorowe)'),
(false, '762', 'Wózki jezdniowe podnośnikowe, mechaniczne, wysokiego podnoszenia (widłowe) o napędzie elektrycznym (akumulatorowe)'),
(false, '763', 'Wózki jezdniowe podnośnikowe, mechaniczne, wysokiego podnoszenia (widłowe) o napędzie spalinowym'),
(false, '764', 'Wózki jezdniowe transportowe ze stałą platformą i żurawiem   o napędzie elektrycznym (akumulatorowe)'),
(false, '768', 'Pozostałe wózki jezdniowe'),
(false, '77', 'TABOR PŁYWAJĄCY'),
(false, '770', 'Tabor transportu morskiego'),
(false, '771', 'Tabor rybołówstwa morskiego'),
(false, '772', 'Tabor techniczny i ratowniczy morski'),
(false, '773', 'Tabor transportu śródlądowego'),
(false, '774', 'Tabor techniczny i ratowniczy śródlądowy'),
(false, '778', 'Pozostały tabor pływający'),
(false, '78', 'TABOR LOTNICZY'),
(false, '780', 'Samoloty'),
(false, '781', 'Śmigłowce'),
(false, '782', 'Szybowce'),
(false, '783', 'Balony'),
(false, '788', 'Pozostałe środki transportu lotniczego'),
(false, '79', 'Pozostałe środki transportu'),
(false, '790', 'Pozostałe środki transportu'),
(false, '8', 'NARZĘDZIA, PRZYRZĄDY, RUCHOMOŚCI I WYPOSAŻENIE, GDZIE INDZIEJ NIESKLASYFIKOWANE'),
(false, '80', 'NARZĘDZIA, PRZYRZĄDY, RUCHOMOŚCI I WYPOSAŻENIE, GDZIE INDZIEJ NIESKLASYFIKOWANE'),
(false, '800', 'Narzędzia, przyrządy, sprawdziany itp.'),
(false, '801', 'Wyposażenie, aparaty i sprzęt laboratoryjny'),
(false, '802', 'Wyposażenie, aparaty i sprzęt medyczny'),
(false, '803', 'Wyposażenie techniczne dla prac biurowych'),
(false, '804', 'Wyposażenie i sprzęt cyrkowy'),
(false, '805', 'Wyposażenie i sprzęt kin, teatrów i innych placówek kulturalno-oświatowych'),
(false, '806', 'Kioski, budki, baraki, domki campingowe itp.'),
(false, '808', 'Pozostałe narzędzia, przyrządy, ruchomości i wyposażenie, gdzie indziej niesklasyfikowane'),
(false, '9', 'INWENTARZ ŻYWY'),
(false, '90', 'INWENTARZ ŻYWY_'),
(false, '900', 'Inwentarz żywy');