package com.alex.asset.product.domain;

public enum Activity {
    VISIBILITY, PRODUCT_WAS_CREATED,
    TITLE, PRICE,
    BAR_CODE, RFID_CODE, INVENTORY_NUMBER, SERIAL_NUMBER,
    LIABLE, RECEIVER,
    KST, ASSET_STATUS, UNIT, BRANCH, MPK, LOCATION,
    TYPE, SUBTYPE, PRODUCER, SUPPLIER,
    SCRAPPING,
    DOCUMENT, DOCUMENT_DATE, WARRANTY_PERIOD,
    INSPECTION_DATE,
    GPS,


    COMMENT
}
