package com.alex.asset.utils;

public enum ErrorStatus {

    USER_ALREADY_EXISTS,
    ACCESS_DENIED,
    USER_NOT_ENABLED,

    ACCOUNT_ACTIVATED,
    PASSWORD_WAS_CHANGED,


    USER_NOT_FOUND,
    INVALID_TOKEN,
    USER_ACCOUNT_DISABLED,
    INVALID_PASSWORD,
    INVALID_DATA,
    INVALID_USERNAME,
    TOKEN_EXPIRED,
    UNAUTHORIZED,
    USER_ALREADY_EXISTS_EXCEPTION,
    INTERNAL_SERVER_ERROR
}
